# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_timestamp', models.DateTimeField()),
                ('queue_enter_time', models.DateTimeField()),
                ('caller_id_num', models.CharField(max_length=30)),
                ('caller_id_name', models.CharField(max_length=100)),
                ('queue_name', models.CharField(max_length=30)),
                ('queue_id', models.UUIDField()),
                ('session_id', models.UUIDField()),
                ('event_name', models.CharField(max_length=30)),
                ('recipient_id', models.UUIDField()),
                ('recipient_name', models.CharField(max_length=30)),
                ('total_wait_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JiraTriggerConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_wait_time', models.IntegerField()),
                ('queue_name', models.CharField(max_length=30)),
                ('caller_id_name', models.CharField(max_length=100)),
                ('recipient_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='callcenterapp.CallDetail')),
            ],
        ),
    ]
